In [25]:
# import
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
#from sklearn.datasets import load_wine

# prep dataframe
data = pd.read_csv('DelinquentBusinessLicenses.csv', usecols=[1, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 23, 24, 25])

In [26]:
data.columns

Index(['FULL NAME', 'PROCESSED DATE', 'START DATE', 'EXPIRE DATE',
       'INACTIVE DATE', 'MILESTONE DATE', 'MILESTONE', 'PROPERTY TYPE',
       'SITE LOCATION', 'COMPANY TYPE', '#EMPLOYEES', '#VEHICLES', '#STANDS',
       '#SEATS', '#UNITS', 'COUNCIL DISTRICT', 'BID AREA',
       'APPLICATION DESCRIPTION'],
      dtype='object')

In [27]:
# prep dataframe

df = pd.DataFrame(
    data=data["START DATE"],
    columns=data["COMPANY TYPE"]
)
df["#EMPLOYEES"] = data["#EMPLOYEES"]

# inspect df
df.head()

COMPANY TYPE,CORP,CORP,CORP,TRUST,CORP,PARTNER,PARTNER,SOLE,SOLE,SOLE,...,LLC,SOLE,LLC,CORP,nan,LLC,SOLE,SOLE,CORP,#EMPLOYEES
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [29]:
classes, counts = np.unique(
    data["PARTNER"],
    return_counts=True
)

# actual plot
for (cls, cnt) in zip(classes, counts):
    plt.bar(
        x=cls,
        height=cnt,
        label="COMPANY TYPE {cls}".format(**locals())
    )
plt.legend(loc=0)
plt.xticks([1, 2, 3])
plt.title("Count by COMPANY TYPE");

KeyError: 'PARTNER'